### ISSUE TITLE
kube-dns & kube-dashboard not up issue

### ISSUE THREAD

**Issue by simonschuang** [cdxvirt/k8sup#29]
Deploy 3 nodes cluster, after deployment, kube-dns & kube-dashboard not run correctly.
$ kubectl describe --namespace=kube-system pod kube-dns-v17.1-zc7an
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  22m		22m		1	{default-scheduler }			Normal		Scheduled		Successfully assigned kube-dns-v17.1-zc7an to 192.168.33.96
  22m		22m		1	{default-scheduler }			Normal		FailedScheduling	Binding rejected: Operation cannot be fulfilled on pods/binding "kube-dns-v17.1-zc7an": pod kube-dns-v17.1-zc7an is already assigned to node "192.168.33.96"
  22m		1s		841	{kubelet 192.168.33.96}			Warning		FailedSync		Error syncing pod, skipping: failed to "SetupNetwork" for "kube-dns-v17.1-zc7an_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kube-dns-v17.1-zc7an_kube-system(deab6e9a-b2c2-11e6-97d0-00089befb2ea)\" using network plugins \"cni\": could not find \".\" plugin; Skipping pod"

**Comment by hsfeng** [comment]
#43
